baseurl: https://blog.xenol.eu
disablePathToLower: true
languageCode: en-us
title: xenol's blog
metadataformat: yaml

theme: octopress

markup:
  goldmark:
    renderer:
      unsafe: true

paginate: 6

permalinks:
  post: /blog/:year/:month/:day/:title/
  talk: /talk/:year/:month/:day/:title/

indexes:
  tag: tags
  category: categories

menu:
  main:
    - name: "Blog"
      url: "/"
      weight: 5
    - name: "Talks"
      url: "/talks"
      weight: 10
    - name: "Archives"
      url: "/archives"
      weight: 15
    - name: "About"
      url: "/about"
      weight: 20

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

params:
  # number of recent posts that will be shown in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit: 5

  # search engine parameter in the navigation menu
  searchEngineUrl: "https://www.google.com/search"

  # sidebar customization - passed to markdownify
  sidebarHeader: ""

  # sidebar text supports markdown
  sidebarText: ""

  # social
  github: "https://github.com/xen0l/"
  bitbucket: "https://bitbucket.org/xenol/"
  twitter: "https://twitter.com/xen0l/"
  linkedin: "https://sk.linkedin.com/in/xenol"
  keybase: "https://keybase.io/xenol/"

  # sidebar menu
  # if true will add a sidebar menu between sidebar text and recent posts
  sidebarMenuEnabled: false
  sidebarMenuHeader: "Sidebar Links"

  # if false, all of posts' content will appear on front page (and in pagination) - not recommended
  # be sure to use the  delimiter
  truncate: true

  # author's name (this will appear in metadata and at the bottom of posts)
  author: "xenol"

  # appears in the site header under website title
  subtitle: "Chance favors the prepared mind"

  # text of the Continue Reading label - if not set, it will default to "Read On &rarr;"
  # &rarr; == right arrow, but it gets messed up in the string so it is added to hugo-octopress/layouts/index.html manually
  # this can be modified in hugo-octopress/layouts/index.html
  continueReading: "Continue reading"

  # disqus - simply enter your disqus - using the template from https://gohugo.io/extras/comments/ at /hugo-octopress/layouts/partials/disqus.html that disables disqus when running on localhost (if you are testing it offline remember to comment out the if in the template that checks for localhost)
  # the template is injected into the pages in /hugo-octopress/layouts/partials/post-footer.html which is in every post (and not non-post pages like license.html)
  disqusShortname: "xenolsblog"

  # Google analytics - _internal/googleanalytics.html in injected in hugo-octopress/layouts/partials/header.html
  googleAnalytics: "UA-32163480-1"

  # switch to true to enable RSS icon link in the navigation menu
  rss: true

  # Website's default description used in meta tags
  defaultDescription: ""

  # keywords used in meta tags
  # defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  # override the built-in css
  # custom_css = ["css/custom.css","css/custom2.css"]

  # enable/disable Table of Contents in each page -
  tableOfContents: false

  # 404.html header and text -both support markdown
  notFoundHeader: "There's nothing here"
  notFoundText: "Please either go back or use the navigation/sidebar menus."

  # Set to true to hide ReadingTime on posts
  disableReadingTime: false

